title: Xi Bai''s Homepage
email: xi.bai.ed@gmail.com
description: > 
  Xi''s personal site
baseurl: ""
url: "http://baixi.info"
twitter_username: baxtree
github_username:  baxtree

# Build settings
markdown: kramdown
