#!/bin/bash

git checkout development
bundle exec jekyll build
rm -rf /tmp/_site
cp -r _site/ /tmp/_site
git checkout master
rm -rf .
cp -r /tmp/_site/ .
git add .
git commit -m "new release"
git push 
git checkout development
